
### Ribbon 配置
ribbon:
    # 连接超时
    ConnectTimeout: 2000
    # 响应超时
    ReadTimeout: 10000

logging:
    level:
        com:
            robotbana: info

server:
    port: 8180
spring:
    application:
        name: order-server
    cloud:
        loadbalancer:
            ribbon:
                enabled: true
#        consul:
#            host: 127.0.0.1
#            port: 8500
        nacos:
            config:
                server-addr: 192.168.101.50:8848
                username: nacos
                password: nacos
            discovery:
                server-addr: 192.168.101.50:8848
                username: nacos
                password: nacos
#        discovery:
#            register: true
#            prefer-ip-address: true
#            health-check-path: /actuator/health
#            service-name: ${spring.application.name}
#            instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
#            health-check-interval: 5s
        alibaba:
            seata:
                tx-service-group: my_tx_group

    aop:  #使用CGLIB来实现AOP的时候
        proxy-target-class: true
    shardingsphere:
        datasource:
            names: ds0,ds1
            ds0:
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.jdbc.Driver
                username: root
                password: 123456
                jdbc-url: jdbc:mysql://192.168.101.24:3306/seata_order_0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
                url: jdbc:mysql://192.168.101.24:3306/seata_order_0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
                filters: stat,wall,log4j
                maxActive: 20
                initialSize: 1
                maxWait: 60000
                minIdle: 1
                timeBetweenEvictionRunsMillis: 60000
                minEvictableIdleTimeMillis: 300000
                validationQuery: select 'x'
                testWhileIdle: true
                testOnBorrow: false
                testOnReturn: false
                poolPreparedStatements: true
                maxOpenPreparedStatements: 20
                connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000
            ds1:
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.jdbc.Driver
                username: root
                password: 123456
                jdbc-url: jdbc:mysql://192.168.101.24:3306/seata_order_1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
                url: jdbc:mysql://192.168.101.24:3306/seata_order_1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
                filters: stat,wall,log4j
                maxActive: 20
                initialSize: 1
                maxWait: 60000
                minIdle: 1
                timeBetweenEvictionRunsMillis: 60000
                minEvictableIdleTimeMillis: 300000
                validationQuery: select 'x'
                testWhileIdle: true
                testOnBorrow: false
                testOnReturn: false
                poolPreparedStatements: true
                maxOpenPreparedStatements: 20
                connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000
        sharding:
            default-database-strategy:
                inline:
                    sharding-column: id
                    algorithm-expression: ds$->{id % 2}
            tables:
                order:
                    actual-data-nodes: ds$->{0..1}.order_$->{0..1}
                    table-strategy:
                        inline:
                            sharding-column: id
                            algorithm-expression: order_$->{id % 2}
                    key-generator:
                        column: id
                        type: SNOWFLAKE
                        props:
                            worker.id: 1


        props:
            sql:
                show: true

mybatis-plus:
    #  datasource: dataSource
    mapper-locations: classpath:/mapper/**/*.xml
    #实体扫描，多个package用逗号或者分号分隔
    type-aliases-package:  com.robotbana.demo.shardingjdbc.mybatisplus.entity
    #typeEnumsPackage: com.baomidou.springboot.entity.enums
    global-config:
        #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID", 4:"该类型为未设置主键类型", 5:"字符串全局唯一ID";
        id-type: 2
        #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
        field-strategy: 1
        #驼峰下划线转换
        db-column-underline: true
        #刷新mapper 调试神器
        refresh-mapper: true
        #数据库大写下划线转换
        #capital-mode: true
        #逻辑删除配置（下面3个配置）
        logic-delete-value: 0
        logic-not-delete-value: 1
        # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
        sql-parser-cache: true
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
    configuration-properties:
        dbType: mysql #设置全局属性用于控制数据库的类型

feign:
    hystrix:
        enabled: true #开启熔断
    compression:
        request:
            enabled: true # 开启对请求的压缩
            mime-types: "[text/xml,application/xml,application/json]" # 指定启用压缩文件的类型
            min-request-size: 1024 # 指定启用压缩的最小文件大小
        response:
            enabled: true # 开启对响应的压缩
    client:
        config:
            default:
                connectTimeout: 30000  # 指定Feign客户端连接提供者的超时时限   取决于网络环境
                readTimeout: 30000   # 指定Feign客户端从请求到获取到提供者给出的响应的超时时限  取决于业务逻辑运算时间
hystrix:
    command:
        default:  #default全局有效，service id指定应用有效
            execution:
                timeout:
                    enabled: true
                isolation:
                    thread:
                        timeoutInMilliseconds: 30000 #断路器超时时间，默认1000ms